import { Listing } from "./types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    title: "Arduino Uno R3 Board",
    description: "Used for one semester project. Works perfectly, comes with USB cable. Great for beginners getting started with microcontrollers.",
    price: 450,
    category: "Arduino",
    condition: "Like New",
    images: [],
    sellerId: "mock-user-1",
    sellerName: "Rahul Sharma",
    sellerPhone: "919876543210",
    college: "IIT Bombay",
    createdAt: "2026-03-10T10:00:00Z",
    sold: false,
    likes: 12,
  },
  {
    id: "2",
    title: "HC-SR04 Ultrasonic Sensor (Pack of 3)",
    description: "Three ultrasonic distance sensors. Used once in robotics project. All working, tested individually.",
    price: 180,
    category: "Sensors",
    condition: "Good",
    images: [],
    sellerId: "mock-user-2",
    sellerName: "Priya Patel",
    sellerPhone: "919876543211",
    college: "NIT Trichy",
    createdAt: "2026-03-08T14:00:00Z",
    sold: false,
    likes: 8,
  },
  {
    id: "3",
    title: "Soldering Station - Hakko FX-888D",
    description: "Professional soldering station in excellent condition. Temperature controlled, includes spare tips. Selling because graduating.",
    price: 2800,
    category: "Tools",
    condition: "Good",
    images: [],
    sellerId: "mock-user-1",
    sellerName: "Rahul Sharma",
    sellerPhone: "919876543210",
    college: "IIT Bombay",
    createdAt: "2026-03-05T09:00:00Z",
    sold: false,
    likes: 24,
  },
  {
    id: "4",
    title: "ESP32 DevKit v1 (WiFi + BLE)",
    description: "ESP32 development board with built-in WiFi and Bluetooth. Perfect for IoT projects. Barely used.",
    price: 350,
    category: "Communication",
    condition: "New",
    images: [],
    sellerId: "mock-user-3",
    sellerName: "Amit Kumar",
    sellerPhone: "919876543212",
    college: "BITS Pilani",
    createdAt: "2026-03-12T16:00:00Z",
    sold: false,
    likes: 15,
  },
  {
    id: "5",
    title: "0.96\" OLED Display Module I2C",
    description: "SSD1306 OLED display, 128x64 pixels. I2C interface, works with Arduino and ESP32. Tested and working.",
    price: 120,
    category: "Displays",
    condition: "Like New",
    images: [],
    sellerId: "mock-user-2",
    sellerName: "Priya Patel",
    sellerPhone: "919876543211",
    college: "NIT Trichy",
    createdAt: "2026-03-11T11:00:00Z",
    sold: false,
    likes: 6,
  },
  {
    id: "6",
    title: "Nema 17 Stepper Motor",
    description: "Bipolar stepper motor, 1.8° step angle. Used in 3D printer project. Comes with mounting screws.",
    price: 300,
    category: "Motors",
    condition: "Good",
    images: [],
    sellerId: "mock-user-3",
    sellerName: "Amit Kumar",
    sellerPhone: "919876543212",
    college: "BITS Pilani",
    createdAt: "2026-03-07T13:00:00Z",
    sold: false,
    likes: 10,
  },
  {
    id: "7",
    title: "18650 Li-ion Battery Pack (4S)",
    description: "Custom 4S battery pack with BMS. 14.8V nominal, ~2600mAh. Great for robotics or drone projects.",
    price: 600,
    category: "Power",
    condition: "Fair",
    images: [],
    sellerId: "mock-user-1",
    sellerName: "Rahul Sharma",
    sellerPhone: "919876543210",
    college: "IIT Bombay",
    createdAt: "2026-03-06T08:00:00Z",
    sold: false,
    likes: 18,
  },
  {
    id: "8",
    title: "Breadboard + Jumper Wire Kit",
    description: "Full-size breadboard with 65 jumper wires (M-M, M-F, F-F). Everything you need to prototype.",
    price: 150,
    category: "Misc",
    condition: "New",
    images: [],
    sellerId: "mock-user-2",
    sellerName: "Priya Patel",
    sellerPhone: "919876543211",
    college: "NIT Trichy",
    createdAt: "2026-03-13T15:00:00Z",
    sold: false,
    likes: 4,
  },
];
